[package]
name = "argfile"
version = "0.1.0"
authors = ["Dan Head <dan@singleops.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exec = "0.3.1"
